### ISSUE TITLE
Error downloading Go language archive

### ISSUE THREAD

**Issue by akavel** [0install/0publish-win#17]
I'm trying to create a feed for the Go language compiler.

  1. I start the "New Feed (Wizard)"
  2. I enter the "Download" URL: https://dl.google.com/go/go1.13.5.windows-amd64.zip
  3. After clicking "Next", during unpacking phase, I am given a message **"The archive file is invalid or damaged"** and the Wizard refuses to proceed to next phase.
  4. To verify that the archive is OK, I download it from the same URL and successfully unpack it with Windows Explorer.

**Comment by bastianeicher** [comment]
We already have a feed for Go: http://repo.roscidus.com/golang/go

I ran into the same issue you did when I originally created that feed.
The Go ZIP archive contains some very long file paths (> 250 characters). The original ZIP specification does not allow such long paths, but there are various extensions that work around it. Unfortunately the Go ZIP archive uses an extension that the library Zero Install uses to extract ZIP archives cannot handle.
To avoid this issue I used the MSI (Windows Installer) packages for Go instead of the ZIP archives in the feed. Zero Install can extract the contents of MSI files like regular archives without actually running the installer and the MSI format has no 250 character limitation.

**Comment by akavel** [comment]
Oh, ok, thanks. I'm confused about all the people's catalogues (that's the name, right?) of 0install feeds; the roscidus one is kinda a central hub, like a "planet" of blogs but for feeds, right?

**Comment by bastianeicher** [comment]
A Zero Install feed can be hosted at an HTTP(S) URL, with or without a catalog listing it.

A `catalog.xml` is an index of multiple feeds hosted on one site. It can be used to search through feeds in the browser or the Zero Install for Windows GUI. The tool [0repo](https://github.com/0install/0repo) creates such catalog files automatically.

http://repo.roscidus.com/ contains the "official" feeds provided by 0install maintainers suchs as @talex5 and myself. You can find feeds for popular apps and common infrastructure stuff like Python and JRE there.
We're currently in the process of renaming it to https://apps.0install.net/ to make it less confusing for new users.
